# Generated by Django 4.1 on 2022-08-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_requisition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='employee',
            field=models.ManyToManyField(to='user.newuser'),
        ),
    ]
