# Generated by Django 4.1 on 2022-08-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_requisition_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='from_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromaemployee', to='user.newuser'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='to_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toaemployee', to='user.newuser'),
        ),
    ]
