# Generated by Django 4.1 on 2022-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_requisition_from_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='from_employee',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='to_employee',
        ),
        migrations.AddField(
            model_name='requisition',
            name='employee',
            field=models.ManyToManyField(to='user.newuser'),
        ),
    ]
