# Generated by Django 4.1 on 2022-08-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_requisition_from_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
