# Generated by Django 4.1 on 2022-08-24 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_requisition_created_by_requisition_date_of_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date_of_delivery',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 24), null=True),
        ),
    ]
