# Generated by Django 4.1 on 2022-08-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_requisition_date_of_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
