# Generated by Django 4.1 on 2022-08-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_requisition_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.newuser'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='employee',
            field=models.ManyToManyField(related_name='to_be_sent_to', to='user.newuser'),
        ),
    ]
