# Generated by Django 4.1 on 2022-08-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_requisition_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='created_by',
            new_name='submitted_by',
        ),
    ]
