# Generated by Django 4.1 on 2022-08-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_employee_requisition_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
