# Generated by Django 4.1 on 2022-08-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_requisition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='send_to',
        ),
        migrations.AddField(
            model_name='requisition',
            name='send_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_be_sent_to', to='user.newuser'),
        ),
    ]
