# Generated by Django 4.1 on 2022-08-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_requisition_send_to_requisition_send_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='send_to',
        ),
    ]
