# Generated by Django 4.1 on 2022-08-26 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_requisition_send_to_requisition_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date_of_delivery',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 26), null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='send_to',
            field=models.ManyToManyField(to='user.newuser'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_be_sent_by', to='user.newuser'),
        ),
    ]
