# Generated by Django 4.1 on 2022-09-02 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_requisition_date_of_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date_of_delivery',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 2), null=True),
        ),
    ]
