# Generated by Django 4.1 on 2022-09-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_newuser_image_alter_requisition_date_of_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='file',
        ),
        migrations.CreateModel(
            name='MultiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user/files/')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.requisition')),
            ],
        ),
    ]
