# Generated by Django 4.1 on 2022-09-04 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_requisition_file_multifile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date_of_delivery',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 4), null=True),
        ),
        migrations.CreateModel(
            name='MultiNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='user.requisition')),
            ],
        ),
    ]
