# Generated by Django 4.1 on 2022-09-06 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_requisition_date_of_delivery_multinote'),
    ]

    operations = [
        migrations.AddField(
            model_name='multinote',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='multinote',
            name='writer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_of_delivery',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 6), null=True),
        ),
    ]
