# Generated by Django 4.1 on 2022-09-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_multinote_date_multinote_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multinote',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='user.newuser'),
        ),
    ]
