# Generated by Django 4.1 on 2022-09-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_multinote_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multinote',
            old_name='writer',
            new_name='written_by',
        ),
    ]
