# Generated by Django 4.1 on 2022-09-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_rename_writer_multinote_written_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multinote',
            name='written_by',
        ),
    ]
