# Generated by Django 4.1 on 2022-09-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_multinote_written'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multinote',
            name='written',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.newuser'),
        ),
    ]
