# Generated by Django 4.1 on 2022-09-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_multinote_written'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multinote',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
