# Generated by Django 4.1 on 2022-09-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_multinote_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multinote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
